import doctorImg1 from '../assets/bacsi.jpg';
import doctorImg2 from '../assets/bacsi1.jpg';
import type {
  DoctorStaff,
  ShiftSchedule,
  LeaveRequest,
  Appointment,
  Branch,
  ServiceItem,
  AiInsightItem,
  SystemAuditLog,
} from '../types/admin';

export const MOCK_DOCTORS: DoctorStaff[] = [
  {
    id: 'nv-001',
    code: 'NV001',
    name: 'BS. Nguyễn Thị An',
    avatar: doctorImg2,
    role: 'Doctor',
    specialty: 'Bác sĩ - Phục hình Răng sứ',
    department: 'Khoa Phục Hình',
    branch: 'Chi nhánh Biên Hòa',
    phone: '0901 234 567',
    email: 'nguyenthian@smartschedule.ai',
    status: 'Active',
    rating: 4.9,
    totalAppointments: 128,
    salaryBase: 35000000,
    allowance: 5000000,
    commission: 15000000,
    commissionRate: 15,
  },
  {
    id: 'nv-002',
    code: 'NV002',
    name: 'PT. Lê Văn Bình',
    avatar: doctorImg1,
    role: 'Nurse',
    specialty: 'Phụ tá - Nội nha',
    department: 'Khoa Nội Nha',
    branch: 'Chi nhánh Biên Hòa',
    phone: '0912 345 678',
    email: 'levanbinh@smartschedule.ai',
    status: 'Active',
    rating: 4.8,
    totalAppointments: 85,
    salaryBase: 18000000,
    allowance: 3000000,
    commission: 5000000,
    commissionRate: 5,
  },
  {
    id: 'nv-003',
    code: 'NV003',
    name: 'BS. Trần Đức Cường',
    avatar: '',
    initials: 'TC',
    role: 'Doctor',
    specialty: 'Bác sĩ - Chỉnh nha',
    department: 'Khoa Chỉnh Nha',
    branch: 'Chi nhánh Biên Hòa',
    phone: '0983 456 789',
    email: 'tranduccuong@smartschedule.ai',
    status: 'OnLeave',
    rating: 5.0,
    totalAppointments: 210,
    salaryBase: 38000000,
    allowance: 5500000,
    commission: 20000000,
    commissionRate: 20,
  },
  {
    id: 'nv-004',
    code: 'NV004',
    name: 'LT. Phạm Thị Dung',
    avatar: doctorImg2,
    role: 'Receptionist',
    specialty: 'Lễ tân',
    department: 'Bộ phận Tiếp Đón',
    branch: 'Chi nhánh Biên Hòa',
    phone: '0934 567 890',
    email: 'phamthidung@smartschedule.ai',
    status: 'Active',
    rating: 0,
    totalAppointments: 0,
    salaryBase: 12000000,
    allowance: 2000000,
    commission: 0,
    commissionRate: 0,
  },
  {
    id: 'doc-1',
    code: 'NV005',
    name: 'TS.BS. Nguyễn Minh Anh',
    avatar: doctorImg1,
    role: 'Doctor',
    specialty: 'Bác sĩ - Tim Mạch & Nội Khoa',
    department: 'Khoa Nội Ca 1',
    branch: 'Cơ sở Quận 1',
    phone: '0903.123.456',
    email: 'minhanh.nguyen@smartschedule.ai',
    status: 'Active',
    rating: 4.9,
    totalAppointments: 1240,
    salaryBase: 35000000,
    allowance: 5000000,
    commission: 12500000,
    commissionRate: 18,
  },
  {
    id: 'doc-2',
    code: 'NV006',
    name: 'BS. CKII. Trần Thị Thu Hương',
    avatar: doctorImg2,
    role: 'Doctor',
    specialty: 'Bác sĩ - Răng Hàm Mặt & Phẫu Thuật',
    department: 'Khoa Nha Khoa Kỹ Thuật Cao',
    branch: 'Cơ sở Quận 1',
    phone: '0918.987.654',
    email: 'thuhuong.tran@smartschedule.ai',
    status: 'Busy',
    rating: 4.85,
    totalAppointments: 980,
    salaryBase: 32000000,
    allowance: 4500000,
    commission: 18200000,
    commissionRate: 22,
  },
  {
    id: 'doc-3',
    code: 'NV007',
    name: 'ThS.BS. Lê Quốc Nam',
    avatar: doctorImg1,
    role: 'Doctor',
    specialty: 'Bác sĩ - Nhi Khoa & Chẩn Đán Hình Ảnh',
    department: 'Khoa Nhi',
    branch: 'Cơ sở Thủ Đức',
    phone: '0987.654.321',
    email: 'quocnam.le@smartschedule.ai',
    status: 'Active',
    rating: 4.92,
    totalAppointments: 1450,
    salaryBase: 30000000,
    allowance: 4000000,
    commission: 9500000,
    commissionRate: 15,
  },
  {
    id: 'doc-4',
    code: 'NV008',
    name: 'BS. Phạm Hoàng Nam',
    avatar: doctorImg2,
    role: 'Doctor',
    specialty: 'Bác sĩ - Da Liễu & Thẩm Mỹ',
    department: 'Khoa Da Liễu',
    branch: 'Cơ sở Phú Mỹ Hưng',
    phone: '0933.112.233',
    email: 'hoangnam.pham@smartschedule.ai',
    status: 'OnLeave',
    rating: 4.78,
    totalAppointments: 820,
    salaryBase: 28000000,
    allowance: 3500000,
    commission: 15400000,
    commissionRate: 16,
  },
  {
    id: 'staff-5',
    code: 'NV009',
    name: 'Điều dưỡng Võ Thị Kim Anh',
    avatar: doctorImg1,
    role: 'Nurse',
    specialty: 'Phụ tá - Điều Dưỡng Trưởng',
    department: 'Khoa Cấp Cứu',
    branch: 'Cơ sở Quận 1',
    phone: '0909.888.777',
    email: 'kimanh.vo@smartschedule.ai',
    status: 'Active',
    rating: 4.9,
    totalAppointments: 540,
    salaryBase: 15000000,
    allowance: 2000000,
    commission: 2500000,
    commissionRate: 8,
  },
];

export const MOCK_SHIFTS: ShiftSchedule[] = [
  {
    id: 'shift-1',
    staffId: 'doc-1',
    staffName: 'TS.BS. Nguyễn Minh Anh',
    role: 'Bác sĩ Nội Tim Mạch',
    date: '2026-09-04',
    startTime: '07:30',
    endTime: '11:30',
    room: 'Phòng 201 - Khám Tim',
    status: 'Scheduled',
  },
  {
    id: 'shift-2',
    staffId: 'doc-2',
    staffName: 'BS. CKII. Tran Thi Thu Huong',
    role: 'Bác sĩ Răng Hàm Mặt',
    date: '2026-09-04',
    startTime: '13:00',
    endTime: '17:00',
    room: 'Phòng 105 - Phẫu Thuật Nha',
    status: 'Scheduled',
  },
  {
    id: 'shift-3',
    staffId: 'doc-3',
    staffName: 'ThS.BS. Le Quoc Nam',
    role: 'Bác sĩ Nhi Khoa',
    date: '2026-09-04',
    startTime: '08:00',
    endTime: '16:30',
    room: 'Phòng 302 - Khoa Nhi',
    status: 'Scheduled',
  },
];

export const MOCK_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'leave-1',
    staffId: 'doc-4',
    staffName: 'BS. Pham Hoang Nam',
    avatar: doctorImg2,
    role: 'Bác sĩ Da Liễu',
    startDate: '2026-09-05',
    endDate: '2026-09-07',
    reason: 'Tham dự Hội thảo Y khoa Quốc tế Da Liễu tại Hà Nội',
    type: 'Annual',
    status: 'Pending',
    createdAt: '2026-09-02 14:30',
  },
  {
    id: 'leave-2',
    staffId: 'staff-5',
    staffName: 'Vo Thi Kim Anh',
    avatar: doctorImg1,
    role: 'Điều dưỡng Trưởng',
    startDate: '2026-09-10',
    endDate: '2026-09-11',
    reason: 'Giải quyết việc cá nhân gia đình',
    type: 'Personal',
    status: 'Approved',
    createdAt: '2026-09-01 09:15',
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'APT-1001',
    patientName: 'Nguyễn Văn An',
    patientPhone: '0912.345.678',
    doctorName: 'TS.BS. Nguyễn Minh Anh',
    doctorId: 'doc-1',
    service: 'Khám Tim Mạch Chuyên Sâu & Siêu Âm',
    branch: 'Cơ sở Quận 1',
    dateTime: '2026-09-04 08:30',
    status: 'Confirmed',
    aiScore: 98,
    aiNote: 'AI xếp lịch tối ưu thời gian chờ dưới 5 phút',
  },
  {
    id: 'APT-1002',
    patientName: 'Trần Thị Mai',
    patientPhone: '0988.777.666',
    doctorName: 'BS. CKII. Tran Thi Thu Huong',
    doctorId: 'doc-2',
    service: 'Nhổ Răng Khôn Kỹ Thuật Sóng Âm',
    branch: 'Cơ sở Quận 1',
    dateTime: '2026-09-04 14:00',
    status: 'InProgress',
    aiScore: 95,
    aiNote: 'Bệnh nhân chuẩn bị sẵn hồ sơ xét nghiệm máu',
  },
  {
    id: 'APT-1003',
    patientName: 'Lê Hoàng Phúc',
    patientPhone: '0934.555.888',
    doctorName: 'ThS.BS. Le Quoc Nam',
    doctorId: 'doc-3',
    service: 'Khám Nhi Tổng Quát & Tiêm Chủng',
    branch: 'Cơ sở Thủ Đức',
    dateTime: '2026-09-04 09:45',
    status: 'Completed',
    aiScore: 99,
    aiNote: 'Hoàn thành khám đúng tiến độ',
  },
];

export const MOCK_AI_INSIGHTS: AiInsightItem[] = [
  {
    id: 'ai-1',
    title: 'Cảnh báo quá tải ca sáng tại Khoa Tim Mạch',
    description:
      'Dự báo số lượng bệnh nhân khám Tim mạch ca sáng ngày 05/09 vượt 35% công suất phòng 201. Đề xuất tự động điều phối thêm 1 bác sĩ dự phòng ca sáng.',
    impactLevel: 'High',
    category: 'Schedule Optimization',
    suggestedAction: 'Áp dụng gợi ý xếp lịch AI',
    timestamp: '10 phút trước',
  },
  {
    id: 'ai-2',
    title: 'Tối ưu công suất ghế nha khoa Cơ sở Q1',
    description:
      'Khoảng trống 45 phút giữa ca 14h và 15h30 phòng Nha 105. Đề xuất gợi ý đôn lịch hẹn cho bệnh nhân Nguyễn Văn B.',
    impactLevel: 'Medium',
    category: 'Resource Allocation',
    suggestedAction: 'Gửi tin nhắn xác nhận bệnh nhân',
    timestamp: '25 phút trước',
  },
];

export const MOCK_BRANCHES: Branch[] = [
  {
    id: 'b-1',
    name: 'Cơ sở Quận 1 (Trung tâm)',
    address: '123 Đường Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP.HCM',
    phone: '028.3822.1111',
    doctorCount: 18,
    roomCount: 12,
    status: 'Active',
  },
  {
    id: 'b-2',
    name: 'Cơ sở Phú Mỹ Hưng (Q7)',
    address: '456 Nguyễn Lương Bằng, Tân Phú, Quận 7, TP.HCM',
    phone: '028.5411.2222',
    doctorCount: 12,
    roomCount: 8,
    status: 'Active',
  },
  {
    id: 'b-3',
    name: 'Cơ sở TP. Thủ Đức',
    address: '789 Võ Văn Ngân, Bình Thọ, TP. Thủ Đức',
    phone: '028.3720.3333',
    doctorCount: 10,
    roomCount: 6,
    status: 'Active',
  },
];

export const MOCK_SERVICES: ServiceItem[] = [
  {
    id: 'srv-1',
    code: 'DV001',
    name: 'Sứ toàn phần Cercon (Đức)',
    category: 'Phục Hình Răng Sứ',
    price: 6000000,
    durationMinutes: 60,
    status: 'Active',
  },
  {
    id: 'srv-2',
    code: 'DV002',
    name: 'Sứ toàn phần Emax',
    category: 'Phục Hình Răng Sứ',
    price: 7000000,
    durationMinutes: 90,
    status: 'Active',
  },
  {
    id: 'srv-3',
    code: 'DV003',
    name: 'Mặt dán Veneer Emax',
    category: 'Thẩm Mỹ Nha Khoa',
    price: 8000000,
    durationMinutes: 90,
    status: 'Active',
  },
  {
    id: 'srv-4',
    code: 'DV004',
    name: 'Tẩy Trắng Răng Công Nghệ Laser',
    category: 'Thẩm Mỹ Nha Khoa',
    price: 5500000,
    durationMinutes: 120,
    status: 'Active',
  },
];

export const MOCK_AUDIT_LOGS: SystemAuditLog[] = [
  {
    id: 'log-1',
    user: 'Admin - Nguyễn Văn Quản Lý',
    action: 'Cập nhật lịch trực bác sĩ Nguyễn Minh Anh',
    module: 'Lịch Làm Việc',
    ipAddress: '14.241.120.45',
    timestamp: '2026-09-03 19:42:10',
    status: 'Success',
  },
  {
    id: 'log-2',
    user: 'AI SmartSchedule Bot',
    action: 'Tự động tính toán lại lộ trình chờ ca sáng',
    module: 'AI Engine',
    ipAddress: '127.0.0.1 (Internal)',
    timestamp: '2026-09-03 19:30:00',
    status: 'Success',
  },
];
