export const CLOUDINARY_ALLON4 = 'https://res.cloudinary.com/dolpobdpw/image/upload/v1789394589/smartschedule_ai/services/xhrybk8wd5nwl89btp7b.jpg';
export const CLOUDINARY_ORTHO = 'https://res.cloudinary.com/dolpobdpw/image/upload/v1789394593/smartschedule_ai/services/zbl0qrhqnoxavsubarkw.jpg';
export const CLOUDINARY_PORCELAIN = 'https://res.cloudinary.com/dolpobdpw/image/upload/v1789394594/smartschedule_ai/services/awsiu55s7nzbbmbnewyn.jpg';
export const CLOUDINARY_IMPLANT = 'https://res.cloudinary.com/dolpobdpw/image/upload/v1789394597/smartschedule_ai/services/jffzudgw58llooasissg.jpg';

export interface DefaultCategoryItem {
  slug: string;
  name: string;
  description: string;
}

export interface DefaultServiceItem {
  catSlug: string;
  code: string;
  name: string;
  standardPrice: number;
  deposit: number;
  warranty: string;
  durationMinutes: number;
  description: string;
  imageUrl?: string;
  isAiRecommended: boolean;
}

export const DEFAULT_SERVICE_CATEGORIES: DefaultCategoryItem[] = [
  {
    slug: 'cay-ghep-implant-don-le',
    name: 'Cấy ghép Implant đơn lẻ',
    description: 'Bảng giá dịch vụ cấy ghép trụ Implant đơn lẻ và phục hình răng sứ đi kèm',
  },
  {
    slug: 'cay-ghep-implant-toan-ham',
    name: 'Cấy ghép Implant toàn hàm (All-on-4 / All-on-6)',
    description: 'Bảng giá dịch vụ cấy ghép phục hình tức thì toàn hàm All on 4, All on 6',
  },
  {
    slug: 'rang-su-tham-my',
    name: 'Răng sứ thẩm mỹ',
    description: 'Bảng giá bọc răng sứ thẩm mỹ, dán sứ Veneer Emax công nghệ cao',
  },
  {
    slug: 'chinh-nha-nieng-rang',
    name: 'Chỉnh nha & Niềng răng',
    description: 'Bảng giá chỉnh hình răng mặt, mắc cài 3M và khay niềng trong suốt Invisalign',
  },
  {
    slug: 'mini-ham-thao-lap',
    name: 'Mini hàm tháo lắp',
    description: 'Bảng giá phục hình bán cố định Mini hàm tháo lắp trên trụ Implant',
  },
  {
    slug: 'thu-thuat-di-kem',
    name: 'Thủ thuật đi kèm',
    description: 'Ghép xương, màng xương sinh học, nâng xoang và khí cụ chỉnh nha chuyên sâu',
  },
  {
    slug: 'nha-khoa-tong-quat',
    name: 'Nha khoa thẩm mỹ & Tổng quát',
    description: 'Tẩy trắng răng Laser Whitening, cạo vôi răng, trám răng thẩm mỹ và điều trị tổng quát',
  },
];

export const DEFAULT_SERVICES_DATA: DefaultServiceItem[] = [
  // ==========================================
  // 1. Cấy ghép Implant đơn lẻ (Ảnh dịch vụ 4)
  // ==========================================
  {
    catSlug: 'cay-ghep-implant-don-le',
    code: 'DV-IMP-01',
    name: 'Trụ Osstem No mount (Hàn Quốc)',
    standardPrice: 13500000,
    deposit: 2000000,
    warranty: 'Trụ 5 năm • Răng Titan 2 năm',
    durationMinutes: 45,
    description: 'Trụ Implant Osstem No mount chuẩn Hàn Quốc, chi phí kinh tế, ăn nhai chắc chắn, phục hình răng Titan bảo hành 2 năm.',
    imageUrl: CLOUDINARY_IMPLANT,
    isAiRecommended: false,
  },
  {
    catSlug: 'cay-ghep-implant-don-le',
    code: 'DV-IMP-02',
    name: 'Trụ Osstem SA (Hàn Quốc)',
    standardPrice: 17500000,
    deposit: 2000000,
    warranty: 'Trụ 7 năm • Răng Titan 2 năm',
    durationMinutes: 45,
    description: 'Trụ Osstem SA công nghệ xử lý bề mặt SA tăng độ bám dính xương hàm, phục hình răng Titan bền đẹp.',
    imageUrl: CLOUDINARY_IMPLANT,
    isAiRecommended: false,
  },
  {
    catSlug: 'cay-ghep-implant-don-le',
    code: 'DV-IMP-03',
    name: 'Trụ Osstem CA (Hàn Quốc)',
    standardPrice: 22500000,
    deposit: 3000000,
    warranty: 'Trụ 10 năm • Răng Zirconia 7 năm',
    durationMinutes: 45,
    description: 'Trụ Osstem CA ngâm dung dịch Canxi Clorua tăng tính ưa máu, tích hợp xương vượt trội, phục hình răng toàn sứ Zirconia.',
    imageUrl: CLOUDINARY_IMPLANT,
    isAiRecommended: false,
  },
  {
    catSlug: 'cay-ghep-implant-don-le',
    code: 'DV-IMP-04',
    name: 'Trụ Hiossen (Mỹ) - Phục hình Răng Zirconia',
    standardPrice: 24500000,
    deposit: 3000000,
    warranty: 'Trụ 15 năm • Răng Zirconia 7 năm',
    durationMinutes: 60,
    description: 'Trụ Hiossen công nghệ Hoa Kỳ, thiết kế ren xoắn giúp phân bổ lực tối ưu, phục hình răng sứ Zirconia cao cấp.',
    imageUrl: CLOUDINARY_IMPLANT,
    isAiRecommended: false,
  },
  {
    catSlug: 'cay-ghep-implant-don-le',
    code: 'DV-IMP-05',
    name: 'Trụ Hiossen (Mỹ) - Phục hình Răng Lava',
    standardPrice: 28000000,
    deposit: 4000000,
    warranty: 'Trụ 15 năm • Răng Lava 15 năm',
    durationMinutes: 60,
    description: 'Trụ Hiossen Hoa Kỳ kết hợp răng toàn sứ Lava Plus 3M thẩm mỹ đỉnh cao, độ cứng và độ trong hoàn hảo, bảo hành 15 năm.',
    imageUrl: CLOUDINARY_IMPLANT,
    isAiRecommended: true,
  },
  {
    catSlug: 'cay-ghep-implant-don-le',
    code: 'DV-IMP-06',
    name: 'Trụ SOI (Hàn Quốc) - Phục hình Răng Zirconia',
    standardPrice: 26500000,
    deposit: 3500000,
    warranty: 'Trụ 15 năm • Răng Zirconia 7 năm',
    durationMinutes: 60,
    description: 'Trụ SOI bề mặt siêu ưa nước liên kết xương nhanh gấp 2 lần, kết hợp răng toàn sứ Zirconia thẩm mỹ cao.',
    imageUrl: CLOUDINARY_IMPLANT,
    isAiRecommended: false,
  },
  {
    catSlug: 'cay-ghep-implant-don-le',
    code: 'DV-IMP-07',
    name: 'Trụ SOI (Hàn Quốc) - Phục hình Răng Lava',
    standardPrice: 30000000,
    deposit: 4000000,
    warranty: 'Trụ 15 năm • Răng Lava 15 năm',
    durationMinutes: 60,
    description: 'Dòng trụ SOI cao cấp kết hợp răng toàn sứ Lava, tương thích sinh học tức thì, độ bền vượt trội suốt 15 năm.',
    imageUrl: CLOUDINARY_IMPLANT,
    isAiRecommended: true,
  },
  {
    catSlug: 'cay-ghep-implant-don-le',
    code: 'DV-IMP-08',
    name: 'Trụ Straumann SLA (Thụy Sỹ) - Phục hình Răng Lava',
    standardPrice: 43000000,
    deposit: 5000000,
    warranty: 'Trụ Trọn đời • Răng Lava 15 năm',
    durationMinutes: 60,
    description: 'Trụ Straumann SLA Thụy Sỹ số 1 thế giới, rút ngắn thời gian lành thương còn 3-4 tuần, phục hình răng sứ Lava, bảo hành trọn đời.',
    imageUrl: CLOUDINARY_IMPLANT,
    isAiRecommended: true,
  },
  {
    catSlug: 'cay-ghep-implant-don-le',
    code: 'DV-IMP-09',
    name: 'Trụ Straumann CA (Thụy Sỹ) - Phục hình Răng Lava',
    standardPrice: 49000000,
    deposit: 6000000,
    warranty: 'Trụ Trọn đời • Răng Lava 15 năm',
    durationMinutes: 60,
    description: 'Trụ Straumann SLActive Thụy Sỹ ưa nước thế hệ mới nhất, cấy ghép chịu lực tức thì, tỷ lệ thành công 99.8%, bảo hành trọn đời.',
    imageUrl: CLOUDINARY_IMPLANT,
    isAiRecommended: true,
  },

  // ==========================================
  // 2. Cấy ghép Implant toàn hàm (Ảnh dịch vụ 1)
  // ==========================================
  {
    catSlug: 'cay-ghep-implant-toan-ham',
    code: 'DV-AON-01',
    name: 'All on 4 Trụ Osstem SA (Hàn Quốc)',
    standardPrice: 120000000,
    deposit: 10000000,
    warranty: 'Trụ 7 năm • Răng Titan 2 năm',
    durationMinutes: 120,
    description: 'Phục hình All-on-4 toàn hàm bằng 4 trụ Osstem SA Hàn Quốc, hàm răng Titan chịu lực ăn nhai tốt, tiết kiệm chi phí tối đa.',
    imageUrl: CLOUDINARY_ALLON4,
    isAiRecommended: false,
  },
  {
    catSlug: 'cay-ghep-implant-toan-ham',
    code: 'DV-AON-02',
    name: 'All on 4 Trụ Hiossen (Mỹ)',
    standardPrice: 180000000,
    deposit: 15000000,
    warranty: 'Trụ 15 năm • Răng Lava 15 năm',
    durationMinutes: 120,
    description: 'Cấy ghép All-on-4 tiêu chuẩn Hoa Kỳ với 4 trụ Hiossen, phục hình trọn bộ hàm răng sứ Lava cao cấp bảo hành 15 năm.',
    imageUrl: CLOUDINARY_ALLON4,
    isAiRecommended: true,
  },
  {
    catSlug: 'cay-ghep-implant-toan-ham',
    code: 'DV-AON-03',
    name: 'All on 4 Trụ Straumann SLA (Thụy Sỹ)',
    standardPrice: 270000000,
    deposit: 20000000,
    warranty: 'Trụ Trọn đời • Răng Lava 15 năm',
    durationMinutes: 120,
    description: 'Phục hình toàn hàm All-on-4 chuẩn y khoa Thụy Sỹ với 4 trụ Straumann SLA tích hợp sinh học vượt trội, bảo hành trọn đời.',
    imageUrl: CLOUDINARY_ALLON4,
    isAiRecommended: true,
  },
  {
    catSlug: 'cay-ghep-implant-toan-ham',
    code: 'DV-AON-04',
    name: 'All on 4 Trụ Straumann Active (Thụy Sỹ)',
    standardPrice: 320000000,
    deposit: 25000000,
    warranty: 'Trụ Trọn đời • Răng Lava 15 năm',
    durationMinutes: 120,
    description: 'Đẳng cấp All-on-4 với 4 trụ Straumann Active Thụy Sỹ, cấy ghép tức thì ngay sau nhổ răng, thẩm mỹ toàn diện, bảo hành trọn đời.',
    imageUrl: CLOUDINARY_ALLON4,
    isAiRecommended: true,
  },
  {
    catSlug: 'cay-ghep-implant-toan-ham',
    code: 'DV-AON-05',
    name: 'All on 6 Trụ Osstem SA (Hàn Quốc)',
    standardPrice: 170000000,
    deposit: 15000000,
    warranty: 'Trụ 7 năm • Răng Titan 2 năm',
    durationMinutes: 150,
    description: 'Phục hình toàn hàm 6 trụ Osstem SA vững chắc, phân bổ lực ăn nhai tối đa cho bệnh nhân mất răng toàn hàm lâu năm.',
    imageUrl: CLOUDINARY_ALLON4,
    isAiRecommended: false,
  },
  {
    catSlug: 'cay-ghep-implant-toan-ham',
    code: 'DV-AON-06',
    name: 'All on 6 Trụ Hiossen (Mỹ)',
    standardPrice: 200000000,
    deposit: 20000000,
    warranty: 'Trụ 15 năm • Răng Lava 15 năm',
    durationMinutes: 150,
    description: 'All-on-6 công nghệ Mỹ 6 trụ Hiossen dàn trải lực tối ưu, mão toàn sứ Lava tinh xảo bảo hành 15 năm.',
    imageUrl: CLOUDINARY_ALLON4,
    isAiRecommended: true,
  },
  {
    catSlug: 'cay-ghep-implant-toan-ham',
    code: 'DV-AON-07',
    name: 'All on 6 Trụ Straumann SLA (Thụy Sỹ)',
    standardPrice: 350000000,
    deposit: 30000000,
    warranty: 'Trụ Trọn đời • Răng Lava 15 năm',
    durationMinutes: 150,
    description: 'Đỉnh cao phục hình toàn hàm 6 trụ Straumann SLA Thụy Sỹ, giải pháp tái tạo cung hàm vĩnh viễn, bảo hành trọn đời.',
    imageUrl: CLOUDINARY_ALLON4,
    isAiRecommended: true,
  },
  {
    catSlug: 'cay-ghep-implant-toan-ham',
    code: 'DV-AON-08',
    name: 'All on 6 Trụ Straumann Active (Thụy Sỹ)',
    standardPrice: 380000000,
    deposit: 30000000,
    warranty: 'Trụ Trọn đời • Răng Lava 15 năm',
    durationMinutes: 150,
    description: 'Giải pháp phục hình toàn hàm cao cấp nhất thế giới với 6 trụ Straumann Active Thụy Sỹ, cấy ghép chịu lực cấp tốc, bảo hành trọn đời.',
    imageUrl: CLOUDINARY_ALLON4,
    isAiRecommended: true,
  },

  // ==========================================
  // 3. Răng sứ thẩm mỹ (Ảnh dịch vụ 3)
  // ==========================================
  {
    catSlug: 'rang-su-tham-my',
    code: 'DV-POR-01',
    name: 'Sứ toàn phần Katana (Nhật Bản)',
    standardPrice: 4000000,
    deposit: 500000,
    warranty: '5 năm',
    durationMinutes: 60,
    description: 'Răng sứ không kim loại Katana Nhật Bản, màu sắc tự nhiên, hoàn toàn lành tính với môi trường nướu.',
    imageUrl: CLOUDINARY_PORCELAIN,
    isAiRecommended: false,
  },
  {
    catSlug: 'rang-su-tham-my',
    code: 'DV-POR-02',
    name: 'Sứ toàn phần Zirconia (Đức)',
    standardPrice: 5000000,
    deposit: 500000,
    warranty: '7 năm',
    durationMinutes: 60,
    description: 'Khung sườn Zirconia nguyên khối từ Đức, độ cứng gấp 7 lần răng thật, không làm đen viền nướu.',
    imageUrl: CLOUDINARY_PORCELAIN,
    isAiRecommended: false,
  },
  {
    catSlug: 'rang-su-tham-my',
    code: 'DV-POR-03',
    name: 'Sứ toàn phần Cercon (Đức)',
    standardPrice: 6000000,
    deposit: 800000,
    warranty: '10 năm',
    durationMinutes: 60,
    description: 'Răng sứ Cercon HT chính hãng Đức công nghệ CAD/CAM chính xác từng micromet, chịu lực ăn nhai cực tốt.',
    imageUrl: CLOUDINARY_PORCELAIN,
    isAiRecommended: true,
  },
  {
    catSlug: 'rang-su-tham-my',
    code: 'DV-POR-04',
    name: 'Sứ toàn phần Emax (Đức)',
    standardPrice: 7000000,
    deposit: 1000000,
    warranty: '12 năm',
    durationMinutes: 60,
    description: 'Sứ thủy tinh Emax Press Đức thấu quang tương đương men răng thật, vân răng sống động, bảo hành 12 năm.',
    imageUrl: CLOUDINARY_PORCELAIN,
    isAiRecommended: true,
  },
  {
    catSlug: 'rang-su-tham-my',
    code: 'DV-POR-05',
    name: 'Sứ toàn phần Lava 3M (Mỹ)',
    standardPrice: 10000000,
    deposit: 1500000,
    warranty: '15 năm',
    durationMinutes: 60,
    description: 'Dòng răng sứ cao cấp bậc nhất Lava Plus 3M USA, hiệu ứng huỳnh quang như răng thật và độ bền 15 năm.',
    imageUrl: CLOUDINARY_PORCELAIN,
    isAiRecommended: true,
  },
  {
    catSlug: 'rang-su-tham-my',
    code: 'DV-VEN-01',
    name: 'Mặt Dán Sứ Veneer Emax Siêu Mỏng (Đức)',
    standardPrice: 8000000,
    deposit: 1000000,
    warranty: '12 năm',
    durationMinutes: 90,
    description: 'Mặt dán sứ Veneer Emax siêu mỏng 0.2 - 0.5mm, bảo tồn tối đa răng thật không cần mài nhỏ, nụ cười chuẩn tỷ lệ vàng.',
    imageUrl: CLOUDINARY_PORCELAIN,
    isAiRecommended: true,
  },

  // ==========================================
  // 4. Chỉnh nha & Niềng răng (Ảnh dịch vụ 2)
  // ==========================================
  {
    catSlug: 'chinh-nha-nieng-rang',
    code: 'DV-ORT-01',
    name: 'Mắc cài kim loại Archist (Hàn Quốc)',
    standardPrice: 28000000,
    deposit: 3000000,
    warranty: 'Trọn gói điều trị',
    durationMinutes: 60,
    description: 'Mắc cài kim loại tiêu chuẩn Hàn Quốc, lực kéo ổn định, chi phí tối ưu cho học sinh và sinh viên.',
    imageUrl: CLOUDINARY_ORTHO,
    isAiRecommended: false,
  },
  {
    catSlug: 'chinh-nha-nieng-rang',
    code: 'DV-ORT-02',
    name: 'Mắc cài Germini - 3M (Kim loại tiêu chuẩn buộc chun 1, Mỹ)',
    standardPrice: 32000000,
    deposit: 4000000,
    warranty: 'Trọn gói điều trị',
    durationMinutes: 60,
    description: 'Mắc cài kim loại Germini hãng 3M Unitek Hoa Kỳ, độ bám dính cao và bo tròn góc êm ái, hạn chế trầy xước niêm mạc.',
    imageUrl: CLOUDINARY_ORTHO,
    isAiRecommended: false,
  },
  {
    catSlug: 'chinh-nha-nieng-rang',
    code: 'DV-ORT-03',
    name: 'Mắc cài Victory - 3M (Kim loại tiêu chuẩn buộc chun 2, Mỹ)',
    standardPrice: 38000000,
    deposit: 5000000,
    warranty: 'Trọn gói điều trị',
    durationMinutes: 60,
    description: 'Mắc cài kim loại Victory cấu tạo rãnh lưu thông minh của 3M USA, giúp răng dịch chuyển nhanh và chuẩn xác.',
    imageUrl: CLOUDINARY_ORTHO,
    isAiRecommended: false,
  },
  {
    catSlug: 'chinh-nha-nieng-rang',
    code: 'DV-ORT-04',
    name: 'Mắc cài Smarlip - 3M (Kim loại tự khóa, Mỹ)',
    standardPrice: 42000000,
    deposit: 5000000,
    warranty: 'Trọn gói điều trị',
    durationMinutes: 60,
    description: 'Mắc cài kim loại tự đóng 3M SmartClip giảm ma sát dây cung, hạn chế đau nhức và kéo dài khoảng cách tái khám.',
    imageUrl: CLOUDINARY_ORTHO,
    isAiRecommended: true,
  },
  {
    catSlug: 'chinh-nha-nieng-rang',
    code: 'DV-ORT-05',
    name: 'Mắc cài Clarity Advance - 3M (Sứ tiêu chuẩn buộc chun, Mỹ)',
    standardPrice: 50000000,
    deposit: 6000000,
    warranty: 'Trọn gói điều trị',
    durationMinutes: 60,
    description: 'Mắc cài sứ thẩm mỹ cao cấp Clarity Advance 3M tệp màu răng tự nhiên, kháng bám màu thực phẩm tối ưu.',
    imageUrl: CLOUDINARY_ORTHO,
    isAiRecommended: true,
  },
  {
    catSlug: 'chinh-nha-nieng-rang',
    code: 'DV-ORT-06',
    name: 'Mắc cài Ultra - 3M (Sứ tự khóa, Mỹ)',
    standardPrice: 60000000,
    deposit: 8000000,
    warranty: 'Trọn gói điều trị',
    durationMinutes: 60,
    description: 'Đỉnh cao mắc cài sứ tự buộc Ultra 3M, tính thẩm mỹ kín đáo và tốc độ điều trị dàn đều răng vượt trội.',
    imageUrl: CLOUDINARY_ORTHO,
    isAiRecommended: true,
  },
  {
    catSlug: 'chinh-nha-nieng-rang',
    code: 'DV-INV-01',
    name: 'Chỉnh nha Invisalign Lite (14 Khay, Mỹ)',
    standardPrice: 80000000,
    deposit: 10000000,
    warranty: 'Trọn gói 14 khay',
    durationMinutes: 45,
    description: 'Khay niềng trong suốt Invisalign Lite của Align Technology USA, gói 14 khay phù hợp tình trạng răng khấp khểnh nhẹ.',
    imageUrl: CLOUDINARY_ORTHO,
    isAiRecommended: false,
  },
  {
    catSlug: 'chinh-nha-nieng-rang',
    code: 'DV-INV-02',
    name: 'Chỉnh nha Invisalign Moderate (26 Khay, Mỹ)',
    standardPrice: 109000000,
    deposit: 15000000,
    warranty: 'Trọn gói 26 khay',
    durationMinutes: 45,
    description: 'Khay niềng vô hình Invisalign Moderate tối đa 26 khay xử lý các ca chen chúc, lệch lạc mức độ trung bình.',
    imageUrl: CLOUDINARY_ORTHO,
    isAiRecommended: true,
  },
  {
    catSlug: 'chinh-nha-nieng-rang',
    code: 'DV-INV-03',
    name: 'Chỉnh nha Invisalign Comprehensive (Không giới hạn khay, BH 5 năm)',
    standardPrice: 120000000,
    deposit: 20000000,
    warranty: '5 năm bảo hành',
    durationMinutes: 45,
    description: 'Gói niềng răng trong suốt toàn diện Comprehensive cao cấp nhất, không giới hạn khay, mô phỏng nụ cười ClinCheck 3D, BH 5 năm.',
    imageUrl: CLOUDINARY_ORTHO,
    isAiRecommended: true,
  },

  // ==========================================
  // 5. Mini hàm tháo lắp (Ảnh dịch vụ 3)
  // ==========================================
  {
    catSlug: 'mini-ham-thao-lap',
    code: 'DV-MIN-01',
    name: 'Mini hàm tháo lắp 2 trụ Osstem SA (Hàn Quốc)',
    standardPrice: 50000000,
    deposit: 5000000,
    warranty: '7 năm',
    durationMinutes: 90,
    description: 'Phục hình bán cố định 2 trụ Implant liên kết thanh khóa locator giữ chặt hàm tháo lắp, không lo xô lệch khi ăn nhai.',
    imageUrl: CLOUDINARY_PORCELAIN,
    isAiRecommended: false,
  },
  {
    catSlug: 'mini-ham-thao-lap',
    code: 'DV-MIN-02',
    name: 'Mini hàm tháo lắp 3 trụ Osstem SA (Hàn Quốc)',
    standardPrice: 60000000,
    deposit: 6000000,
    warranty: '7 năm',
    durationMinutes: 90,
    description: 'Phục hình bán cố định 3 trụ Implant gia cố thêm độ vững ổn và cảm giác ngon miệng cho hàm tháo lắp.',
    imageUrl: CLOUDINARY_PORCELAIN,
    isAiRecommended: false,
  },
  {
    catSlug: 'mini-ham-thao-lap',
    code: 'DV-MIN-03',
    name: 'Mini hàm tháo lắp 4 trụ Osstem SA (Hàn Quốc)',
    standardPrice: 70000000,
    deposit: 7000000,
    warranty: '7 năm',
    durationMinutes: 90,
    description: 'Phục hình 4 trụ Implant nâng đỡ toàn diện hàm tháo lắp cho người lớn tuổi bị tiêu xương sống hàm nhiều.',
    imageUrl: CLOUDINARY_PORCELAIN,
    isAiRecommended: true,
  },

  // ==========================================
  // 6. Thủ thuật đi kèm (Ảnh 4 & Khí cụ Ảnh 2)
  // ==========================================
  {
    catSlug: 'thu-thuat-di-kem',
    code: 'DV-SUR-01',
    name: 'Ghép xương nhân tạo (1 cc)',
    standardPrice: 4000000,
    deposit: 0,
    warranty: 'Thủ thuật phẫu thuật',
    durationMinutes: 30,
    description: 'Kỹ thuật cấy bột xương nhân tạo hoặc đồng loại giúp bù đắp lượng xương hàm bị tiêu hõm trước khi cắm Implant.',
    imageUrl: undefined,
    isAiRecommended: false,
  },
  {
    catSlug: 'thu-thuat-di-kem',
    code: 'DV-SUR-02',
    name: 'Màng xương sinh học Collagen (1 đơn vị)',
    standardPrice: 3500000,
    deposit: 0,
    warranty: 'Vật liệu sinh học',
    durationMinutes: 20,
    description: 'Đặt màng sinh học tái tạo mô có hướng dẫn, bảo vệ vùng ghép xương khỏi sự xâm lấn của biểu mô nướu.',
    imageUrl: undefined,
    isAiRecommended: false,
  },
  {
    catSlug: 'thu-thuat-di-kem',
    code: 'DV-SUR-03',
    name: 'Nâng xoang hàm trên kín / hở (1 răng)',
    standardPrice: 5000000,
    deposit: 0,
    warranty: 'Thủ thuật ngoại khoa',
    durationMinutes: 45,
    description: 'Phẫu thuật bóc tách và nâng cao đáy xoang hàm trên tạo không gian an toàn để cấy ghép trụ Implant.',
    imageUrl: undefined,
    isAiRecommended: false,
  },
  {
    catSlug: 'thu-thuat-di-kem',
    code: 'DV-APP-01',
    name: 'Cắm Minivis neo chặn chỉnh nha (1 vít)',
    standardPrice: 2500000,
    deposit: 0,
    warranty: 'Theo liệu trình',
    durationMinutes: 20,
    description: 'Đặt vít neo chặn chỉnh nha Minivis hỗ trợ kéo lùi răng hô móm và đánh lún khớp cắn hiệu quả.',
    imageUrl: undefined,
    isAiRecommended: false,
  },
  {
    catSlug: 'thu-thuat-di-kem',
    code: 'DV-APP-02',
    name: 'Hàm duy trì sau chỉnh nha (1 hàm)',
    standardPrice: 2500000,
    deposit: 0,
    warranty: '1 năm',
    durationMinutes: 30,
    description: 'Khí cụ hàm duy trì giữ ổn định vị trí chân răng mới sau khi tháo niềng, chống tái phát sai lệch.',
    imageUrl: undefined,
    isAiRecommended: false,
  },
  {
    catSlug: 'thu-thuat-di-kem',
    code: 'DV-APP-03',
    name: 'Hàm duy trì Vivera Invisalign (1 hàm)',
    standardPrice: 15000000,
    deposit: 2000000,
    warranty: '2 năm',
    durationMinutes: 30,
    description: 'Khay duy trì cao cấp Vivera từ hãng Align Technology vật liệu độc quyền bền chắc gấp đôi, trong suốt thẩm mỹ.',
    imageUrl: undefined,
    isAiRecommended: true,
  },
  {
    catSlug: 'thu-thuat-di-kem',
    code: 'DV-APP-04',
    name: 'Hàm Twinblock chức năng chỉnh nha sớm',
    standardPrice: 8000000,
    deposit: 1000000,
    warranty: '1 năm',
    durationMinutes: 45,
    description: 'Khí cụ chức năng hướng dẫn sự tăng trưởng xương hàm cho trẻ em trong độ tuổi phát triển.',
    imageUrl: undefined,
    isAiRecommended: false,
  },
  {
    catSlug: 'thu-thuat-di-kem',
    code: 'DV-APP-05',
    name: 'Hàm nong nhanh RPE / Quadhelix',
    standardPrice: 8000000,
    deposit: 1000000,
    warranty: '1 năm',
    durationMinutes: 45,
    description: 'Khí cụ mở rộng vòm miệng và nong cung hàm hẹp, tạo khoảng trống xếp đều các răng chen chúc.',
    imageUrl: undefined,
    isAiRecommended: false,
  },

  // ==========================================
  // 7. Nha khoa thẩm mỹ & Tổng quát
  // ==========================================
  {
    catSlug: 'nha-khoa-tong-quat',
    code: 'DV-WHT-01',
    name: 'Tẩy Trắng Răng Chuyên Sâu Công Nghệ Laser Whitening',
    standardPrice: 5500000,
    deposit: 300000,
    warranty: '2 năm',
    durationMinutes: 45,
    description: 'Tẩy trắng răng công nghệ ánh sáng Laser kết hợp gel làm trắng chuẩn FDA Hoa Kỳ, răng trắng bật tông, không ê buốt.',
    imageUrl: CLOUDINARY_PORCELAIN,
    isAiRecommended: true,
  },
  {
    catSlug: 'nha-khoa-tong-quat',
    code: 'DV-GEN-01',
    name: 'Cạo vôi răng & Đánh bóng siêu âm Air-Flow',
    standardPrice: 350000,
    deposit: 0,
    warranty: 'Bảo hành 1 tháng',
    durationMinutes: 30,
    description: 'Lấy sạch mảng bám vôi răng bằng đầu rung siêu âm kết hợp phun cát đánh bóng Air-Flow nhẹ nhàng không tổn thương nướu.',
    imageUrl: undefined,
    isAiRecommended: false,
  },
  {
    catSlug: 'nha-khoa-tong-quat',
    code: 'DV-GEN-02',
    name: 'Trám răng thẩm mỹ Composite Nano',
    standardPrice: 500000,
    deposit: 0,
    warranty: '1 năm',
    durationMinutes: 30,
    description: 'Phục hồi răng sâu hoặc sứt mẻ bằng chất liệu trám Composite Nano cao cấp đồng màu men răng thật.',
    imageUrl: undefined,
    isAiRecommended: false,
  },
  {
    catSlug: 'nha-khoa-tong-quat',
    code: 'DV-GEN-03',
    name: 'Nhổ răng khôn không đau máy siêu âm Piezotome',
    standardPrice: 2500000,
    deposit: 300000,
    warranty: 'Tái khám cắt chỉ miễn phí',
    durationMinutes: 45,
    description: 'Nhổ răng khôn mọc lệch, mọc ngầm êm ái bằng sóng siêu âm Piezotome, giảm sưng đau và lành thương nhanh.',
    imageUrl: undefined,
    isAiRecommended: true,
  },
  {
    catSlug: 'nha-khoa-tong-quat',
    code: 'DV-GEN-04',
    name: 'Điều trị tủy răng công nghệ vi phẫu Reciproc',
    standardPrice: 1800000,
    deposit: 200000,
    warranty: '2 năm',
    durationMinutes: 60,
    description: 'Lấy tủy triệt để bằng trâm xoay máy Reciproc kết hợp đo chiều dài tủy điện tử Apex locator, bảo tồn răng thật tối đa.',
    imageUrl: undefined,
    isAiRecommended: false,
  },
];
